### ISSUE TITLE
Redundant?

### ISSUE THREAD

**Issue by ParkerBeck** [ryanholmdahl/MonaMiner#1]
https://github.com/ryanholmdahl/MonaMiner/blob/d344975a6fa9889f17d5dfaab64cb28223b300ad/main.py#L45-L46

The best coin is the one with the most profits right? So coin profits of current device will always be < when current coin != best coin.

**Comment by ryanholmdahl** [comment]
good call, resolved in 505aa8268ad2fefbb434189bc2dfe3c065084260
