### ISSUE TITLE
Profit code clarity

### ISSUE THREAD

**Issue by ParkerBeck** [ryanholmdahl/MonaMiner#4]
https://github.com/ryanholmdahl/MonaMiner/blob/505aa8268ad2fefbb434189bc2dfe3c065084260/profit.py#L4-L19

Consider adding the btc price api to `get_profitability` for consistency:
`if btc <= 0: 
btc = apis.get_bitcoin_price() `

Consider renaming `btc` to `btc_price` or equivalent.

**Comment by ryanholmdahl** [comment]
Do you mean move the API function from `apis` to `profit`? Or move the `apis.get_bitcoin_price()` call from `main` to `profit`?

**Comment by ryanholmdahl** [comment]
Attempted resolution in 0e85b5e2a2d73a2b889dd89f4b902561e6e4d965 and 18786ff55f6dae3ee0b9a9e70bd424075a4b8390 -- let me know what you think.

**Comment by ParkerBeck** [comment]
@ryanholmdahl LGTM, can you go through and double check all the whitespace changes are intentional? I'm not familiar with python styling guidelines so can't give any feedback on that. Moving forward, consider putting Issue commits into an issue # branch and doing a pull request so it's easier to review and clump them. Then you can squash and merge to improve commit log.

**Comment by ryanholmdahl** [comment]
Yeah I'll start branching. The whitespace changes are from PyCharm's automatic reformatting, which I ran to remove unnecessary package dependencies, so they should conform to Python's style guidelines. Closing the issue.
