### ISSUE TITLE
Move API keys from apis.py to config.json

### ISSUE THREAD

**Issue by ParkerBeck** [ryanholmdahl/MonaMiner#7]
It looks like the only key is L30 of apis.py right now.

**Comment by ryanholmdahl** [comment]
This is being addressed in PR #9.

**Comment by ryanholmdahl** [comment]
Partially resolved in 844e3d7f4065833594c02b77061f76d67bd4badb, but not ideal. We should move API keys and other user-specific info to a separate .json file.
